/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvertisingRouteImport } from './routes/advertising'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SocialMediaMarketingRouteImport } from './routes/social-media-marketing'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ServiceSlugRouteImport } from './routes/service.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingRoute = AdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaMarketingRoute = SocialMediaMarketingRouteImport.update({
  id: '/social-media-marketing',
  path: '/social-media-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSlugRoute = ServiceSlugRouteImport.update({
  id: '/service/$slug',
  path: '/service/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/social-media-marketing': typeof SocialMediaMarketingRoute
  '/work': typeof WorkRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/social-media-marketing': typeof SocialMediaMarketingRoute
  '/work': typeof WorkRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/onboarding': typeof OnboardingRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/social-media-marketing': typeof SocialMediaMarketingRoute
  '/work': typeof WorkRoute
  '/service/$slug': typeof ServiceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertising'
    | '/analytics'
    | '/campaigns'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/reviews'
    | '/services'
    | '/social-media-marketing'
    | '/work'
    | '/service/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertising'
    | '/analytics'
    | '/campaigns'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/reviews'
    | '/services'
    | '/social-media-marketing'
    | '/work'
    | '/service/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertising'
    | '/analytics'
    | '/campaigns'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/messages'
    | '/onboarding'
    | '/reviews'
    | '/services'
    | '/social-media-marketing'
    | '/work'
    | '/service/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertisingRoute: typeof AdvertisingRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignsRoute: typeof CampaignsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  OnboardingRoute: typeof OnboardingRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  SocialMediaMarketingRoute: typeof SocialMediaMarketingRoute
  WorkRoute: typeof WorkRoute
  ServiceSlugRoute: typeof ServiceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising': {
      id: '/advertising'
      path: '/advertising'
      fullPath: '/advertising'
      preLoaderRoute: typeof AdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media-marketing': {
      id: '/social-media-marketing'
      path: '/social-media-marketing'
      fullPath: '/social-media-marketing'
      preLoaderRoute: typeof SocialMediaMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$slug': {
      id: '/service/$slug'
      path: '/service/$slug'
      fullPath: '/service/$slug'
      preLoaderRoute: typeof ServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertisingRoute: AdvertisingRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignsRoute: CampaignsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  OnboardingRoute: OnboardingRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  SocialMediaMarketingRoute: SocialMediaMarketingRoute,
  WorkRoute: WorkRoute,
  ServiceSlugRoute: ServiceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
